### ISSUE TITLE
fix?

### ISSUE THREAD

**Issue by FouadTaissate** [Maaike0904/performance-matters-optimized-website#2]
https://github.com/Maaike0904/performance-matters-optimized-website/blob/07288fbae5ae41e61a60ff4e8bd4be0bc8c9ab65/package.json#L5

Probeer hier "index.js" in te vullen in plaats van "app.js". Dit kan de errors omgaande "app is not defined" oplossen.

**Comment by Maaike0904** [comment]
Heb het aangepast, het is gelukt ! 😄
